---
abstract: 'Imports additional useful methods to Moose::Autobox'
author:
  - 'Michael Swearingen <mswearingen@gmail.com>'
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Autobox-More
no_index:
  directory:
    - inc
    - t
provides:
  MooseX::Autobox::More:
    file: lib/MooseX/Autobox/More.pm
    version: 0.01
  MooseX::Autobox::More::Array:
    file: lib/MooseX/Autobox/More/Array.pm
requires:
  Moose: 0.42
  Moose::Autobox: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
